---

- hosts: all
  become: true 
  tasks: 

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks: 

  - name: install apache2 and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

  - name: install apache2 and php package
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name : change email address of admin
    tags: change_file
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin pippo@pippo.com
    when: ansible_distribution == "CentOS"
    register: httpd
    
  - name: restart httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: file
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: all
  become: true
  tasks:
    
  - name: create simone user
    user:
      name: simone 
      groups: root

  - name: add ssh key for simone
    authorized_key:
      user: simone
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBm1rL9Dt/G9ZHP0hz2Bh5PryMeuP/Pgy6ea6uuGe7zX4TZcwZ9UhduDPHbbPzfeYsqoXdTDU0tYOc9wqB8iIyLoyw8+DOWXUygylvHcR+ITeclKNr4nB9cbQDCVYQT26Rd66W3YVoiyVnVkv3Kd7rM1usFfUp/ssbxX4RwSulPlJ/eQsxsslTC3Z3AUQz38nRnQ3xRytioQ4E87jGrtGJwym0vB2kt9Eq1KSHKQU180BZ4ass+FlWjv66gbI3oksfWUD8T7ZF6Ni2jt7NccKDi6JsNcrctKThHgZONdKxFI60z3LWuSpmVRRFWDq1Z3kVm0EfpMrBKyqHVvbtPAsOzTsXTjBB+Kzc4whu9Ifa5wEO2/QdHO0ApwT0VgLU4yHTXy4NaO9PQ7/OoM2OtJ/CIYMJYu0UoAw/GWg8vrzZyolVZYzQHC0ZalZWCVR7h9UxBbUavI2P0Idy8PgyL5omtj5eyRtZwNCs/Sajv9ofW8gdzVYvZyWNsxUufdt4LbU= ansible"

  - name: add sudoers file for simone
    copy:
      src: sudoers_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

