- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBm1rL9Dt/G9ZHP0hz2Bh5PryMeuP/Pgy6ea6uuGe7zX4TZcwZ9UhduDPHbbPzfeYsqoXdTDU0tYOc9wqB8iIyLoyw8+DOWXUygylvHcR+ITeclKNr4nB9cbQDCVYQT26Rd66W3YVoiyVnVkv3Kd7rM1usFfUp/ssbxX4RwSulPlJ/eQsxsslTC3Z3AUQz38nRnQ3xRytioQ4E87jGrtGJwym0vB2kt9Eq1KSHKQU180BZ4ass+FlWjv66gbI3oksfWUD8T7ZF6Ni2jt7NccKDi6JsNcrctKThHgZONdKxFI60z3LWuSpmVRRFWDq1Z3kVm0EfpMrBKyqHVvbtPAsOzTsXTjBB+Kzc4whu9Ifa5wEO2/QdHO0ApwT0VgLU4yHTXy4NaO9PQ7/OoM2OtJ/CIYMJYu0UoAw/GWg8vrzZyolVZYzQHC0ZalZWCVR7h9UxBbUavI2P0Idy8PgyL5omtj5eyRtZwNCs/Sajv9ofW8gdzVYvZyWNsxUufdt4LbU= ansible"

